# git clone --depth 1 https://github.com/marlonrichert/zsh-snap.git ~/.config/zsh/zsh-snap
if [[ -r "${HOME}/.cache/p10k-instant-prompt-${USERNAME}.zsh" ]]; then
  source "${HOME}/.cache/p10k-instant-prompt-${USERNAME}.zsh"
fi

source ~/.config/zsh/zsh-snap/znap.zsh

znap prompt romkatv/powerlevel10k
znap source zdharma-continuum/fast-syntax-highlighting
znap source zsh-users/zsh-autosuggestions

HISTFILE=~/.cache/zh
HISTSIZE=100
SAVEHIST=300
setopt appendhistory

autoload -Uz compinit
compinit -i

# vi mode settings:
bindkey -v
export KEYTIMEOUT=6
bindkey -M viins "jk" vi-cmd-mode

function zle-line-init zle-keymap-select {
  case ${KEYMAP} in
    vicmd) echo -ne '\e[2 q';;
    viins|main) echo -ne '\e[6 q';;
  esac
}
zle -N zle-line-init
zle -N zle-keymap-select

# aliases:
alias ls='ls --color=auto'
alias c='clear'

# git aliases
alias gco='git checkout'
alias gd='git diff'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gu='git pull'
alias gl='git log --oneline'
alias gst='git status --short'
alias gb='git branch'
alias gcl='git clone --depth 1'
alias gr='git remote'

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
