if [[ -r "${HOME}/.cache/p10k-instant-prompt-${USERNAME}.zsh" ]]; then
  source "${HOME}/.cache/p10k-instant-prompt-${USERNAME}.zsh"
fi

# git clone --depth 1 https://github.com/marlonrichert/zsh-snap.git ~/.config/zsh/zsh-snap
source ~/.config/zsh/zsh-snap/znap.zsh


# znap source marlonrichert/zsh-autocomplete
# znap source ohmyzsh/ohmyzsh
znap source zsh-users/zsh-autosuggestions
znap source zsh-users/zsh-syntax-highlighting
znap prompt romkatv/powerlevel10k

HISTFILE=~/.cache/.zh
HISTSIZE=300
SAVEHIST=100
setopt appendhistory

autoload -Uz compinit
compinit -i

# aliases:
alias ls='ls --color=auto'
alias btw='fastfetch'
alias c='clear'

alias gco='git checkout'
alias gd='git diff'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gu='git pull'
alias gl='git log --oneline'
alias gb='git branch'
alias gi='git init'
alias gcl='git clone --depth 1'
alias gst='git status --short'

# export ssh env
export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/ssh-agent.socket"

# vi mode settings:
bindkey -v
export KEYTIMEOUT=10
bindkey -M viins "jk" vi-cmd-mode

function zle-line-init zle-keymap-select {
    case ${KEYMAP} in
        vicmd) echo -ne '\e[2 q';;
        viins|main) echo -ne '\e[6 q';;
    esac
}
zle -N zle-line-init
zle -N zle-keymap-select

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
