#!/bin/bash

pm() {
  echo -e "\e[1;32m$1\e[0m"
}


pm "Refreshing pacman keys..."
sudo pacman -Sy archlinux-keyring --noconfirm
sudo pacman-key --init
sudo pacman-key --populate archlinux
#sudo pacman-key --refresh-keys

pm "System upgrade..."
sudo pacman -Syyu --noconfirm

pm "Clear cache..."
sudo paccache -rk3

pm "Remove unused packages..."
orphaned_packages=$(pacman -Qdtq)
if [ -n "$orphaned_packages" ]; then
  sudo pacman -Rns $orphaned_packages --noconfirm
else
  echo -e "\e[1;31mNo unused packages to remove.\e[0m"
fi

pm "Clear cache pacman..."
sudo pacman -Scc --noconfirm

pm "________________PACMAN_END________________"
