# git clone --depth 1 https://github.com/marlonrichert/zsh-snap.git ~/.config/zsh/zsh-snap
if [[ -r "${HOME}/.cache/p10k-instant-prompt-${USERNAME}.zsh" ]]; then
  source "${HOME}/.cache/p10k-instant-prompt-${USERNAME}.zsh"
fi

source ~/.config/zsh/zsh-snap/znap.zsh

znap prompt romkatv/powerlevel10k
znap source zdharma-continuum/fast-syntax-highlighting
znap source zsh-users/zsh-autosuggestions

HISTFILE=~/.cache/zh
HISTSIZE=100
SAVEHIST=300
setopt appendhistory

autoload -Uz compinit
compinit -i

# vi mode settings:
bindkey -v
export KEYTIMEOUT=10
bindkey -M viins "jk" vi-cmd-mode

# aliases:
alias ls='ls --color=auto'
alias c='clear'

# git aliases
alias gco='git checkout'
alias gw='git switch'
alias gd='git diff'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gu='git pull'
alias gl='git log --oneline'
alias gst='git status --short'
alias gb='git branch'
alias gcl='git clone --depth 1'
alias gr='git remote'

# make aliases
alias m='make'
alias mc='make clean'
alias mi='make install'

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
