git_branch() {
  local branch
  branch=$(git symbolic-ref --short HEAD 2> /dev/null) || return
  echo "%F{magenta}(${branch})%f"
}

setopt PROMPT_SUBST
PROMPT='%F{green}%n@%m%f:%F{blue}%~%f $(git_branch)$( [[ $? == 0 ]] && echo "%F{cyan}✔%f" || echo "%F{red}✘%f") %# '

HISTFILE="~/.cache/zh"
HISTSIZE=1000
SAVEHIST=3000
setopt appendhistory
setopt sharehistory
setopt hist_ignore_dups
setopt hist_reduce_blanks
setopt extended_glob

setopt auto_menu
setopt auto_list

autoload -Uz compinit
compinit -i

bindkey -v
bindkey -M viins "jk" vi-cmd-mode
bindkey '^R' history-incremental-search-backward

alias ls='ls --color=auto'
alias c='clear'
alias clear=''

alias gco='git checkout'
alias gw='git switch'
alias gd='git diff'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gu='git pull'
alias gl='git log --oneline --graph --all'
alias gs='git status --short'
alias gb='git branch'
alias gcl='git clone --depth 1'
alias gr='git remote'

alias m='make'
alias mc='make clean'
alias mi='make install'
alias mr='make rebuild'

export GPG_TTY=$TTY

zstyle ':completion:*' list-colors 'di=34:fi=0:ln=36'
